
//import static java.awt.SystemColor.text;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bruno
 */
public class MainFrame extends javax.swing.JFrame {
    private boolean saved = false;
    boolean canceled;
    File fileToSave;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jDialogNew = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButtonConfYes = new javax.swing.JButton();
        jButtonConfNo = new javax.swing.JButton();
        jButtonConfCancel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDialogAbout = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDialogExit = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButtonExitYes = new javax.swing.JButton();
        jButtonExitNo = new javax.swing.JButton();
        jButtonExitCancel = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuNew = new javax.swing.JMenuItem();
        jMenuOpen = new javax.swing.JMenuItem();
        jMenuSave = new javax.swing.JMenuItem();
        jMenuSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuExit = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jFileChooser.setAcceptAllFileFilterUsed(false);

        jDialogNew.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogNew.setTitle("New File");
        jDialogNew.setAlwaysOnTop(true);
        jDialogNew.setMaximumSize(new java.awt.Dimension(210, 90));
        jDialogNew.setMinimumSize(new java.awt.Dimension(210, 90));
        jDialogNew.setPreferredSize(new java.awt.Dimension(210, 90));
        jDialogNew.setResizable(false);

        jLabel1.setText("Save before new?");

        jButtonConfYes.setText("Yes");
        jButtonConfYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfYesActionPerformed(evt);
            }
        });

        jButtonConfNo.setText("No");
        jButtonConfNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfNoActionPerformed(evt);
            }
        });

        jButtonConfCancel.setText("Cancel");
        jButtonConfCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogNewLayout = new javax.swing.GroupLayout(jDialogNew.getContentPane());
        jDialogNew.getContentPane().setLayout(jDialogNewLayout);
        jDialogNewLayout.setHorizontalGroup(
            jDialogNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewLayout.createSequentialGroup()
                .addGroup(jDialogNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogNewLayout.createSequentialGroup()
                        .addComponent(jButtonConfYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfNo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfCancel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogNewLayout.setVerticalGroup(
            jDialogNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jDialogNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfYes)
                    .addComponent(jButtonConfNo)
                    .addComponent(jButtonConfCancel)))
        );

        jButton3.setText("jButton3");

        jDialogAbout.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogAbout.setTitle("ABOUT");
        jDialogAbout.setAlwaysOnTop(true);
        jDialogAbout.setMaximumSize(new java.awt.Dimension(210, 90));
        jDialogAbout.setMinimumSize(new java.awt.Dimension(210, 90));
        jDialogAbout.setPreferredSize(new java.awt.Dimension(210, 90));
        jDialogAbout.setResizable(false);

        jLabel2.setText("Made by: Bruno");

        jLabel3.setText("V1.5 - 2018");

        javax.swing.GroupLayout jDialogAboutLayout = new javax.swing.GroupLayout(jDialogAbout.getContentPane());
        jDialogAbout.getContentPane().setLayout(jDialogAboutLayout);
        jDialogAboutLayout.setHorizontalGroup(
            jDialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jDialogAboutLayout.setVerticalGroup(
            jDialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jDialogExit.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogExit.setTitle("Exit");
        jDialogExit.setAlwaysOnTop(true);
        jDialogExit.setMaximumSize(new java.awt.Dimension(210, 90));
        jDialogExit.setMinimumSize(new java.awt.Dimension(210, 90));
        jDialogExit.setPreferredSize(new java.awt.Dimension(210, 90));
        jDialogExit.setResizable(false);

        jLabel4.setText("Save before exit?");

        jButtonExitYes.setText("Yes");
        jButtonExitYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitYesActionPerformed(evt);
            }
        });

        jButtonExitNo.setText("No");
        jButtonExitNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitNoActionPerformed(evt);
            }
        });

        jButtonExitCancel.setText("Cancel");
        jButtonExitCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogExitLayout = new javax.swing.GroupLayout(jDialogExit.getContentPane());
        jDialogExit.getContentPane().setLayout(jDialogExitLayout);
        jDialogExitLayout.setHorizontalGroup(
            jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogExitLayout.createSequentialGroup()
                .addGroup(jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogExitLayout.createSequentialGroup()
                        .addComponent(jButtonExitYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExitNo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExitCancel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogExitLayout.setVerticalGroup(
            jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogExitLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addGroup(jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExitYes)
                    .addComponent(jButtonExitNo)
                    .addComponent(jButtonExitCancel)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NotePad by Bruno");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setText("Save");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Open");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenuFile.setText("File");
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewFile.png"))); // NOI18N
        jMenuNew.setText("New");
        jMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuNew);

        jMenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Open.png"))); // NOI18N
        jMenuOpen.setText("Open File");
        jMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuOpen);

        jMenuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save.png"))); // NOI18N
        jMenuSave.setText("Save");
        jMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuSave);

        jMenuSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SaveAs.png"))); // NOI18N
        jMenuSaveAs.setText("Save as...");
        jMenuSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveAsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuSaveAs);
        jMenuFile.add(jSeparator1);

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuExit);

        jMenuBar1.add(jMenuFile);

        jMenuAbout.setText("About");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/About.png"))); // NOI18N
        jMenuItem1.setText("Info");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAbout.add(jMenuItem1);

        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveActionPerformed
        if (saved)
        {
            canceled=false;
            BufferedWriter bw=null;
            try {
                bw = new BufferedWriter(new FileWriter(fileToSave));
                bw.write(jTextArea.getText());
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally
            {
                if(bw != null)
                {
                    try {
                        bw.close();
                    } catch (IOException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
        }
        else
        {
            jMenuSaveAsActionPerformed(evt);
        }
    }//GEN-LAST:event_jMenuSaveActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        jDialogExit.setVisible(true);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpenActionPerformed
       int returnVal = jFileChooser.showOpenDialog(this);
       if (returnVal == JFileChooser.APPROVE_OPTION) 
       {
        File file = jFileChooser.getSelectedFile();
        try 
        {
          // What to do with the file, e.g. display it in a TextArea
          jTextArea.read( new FileReader( file.getAbsolutePath() ), null );
        } 
        catch (IOException ex) 
        {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
       }
    }//GEN-LAST:event_jMenuOpenActionPerformed

    private void jMenuSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveAsActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");   
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) 
        {
        canceled=false;
        fileToSave = fileChooser.getSelectedFile();
        BufferedWriter bw = null;
            try {
                //fileToSave.createNewFile();
                bw = new BufferedWriter(new FileWriter(fileToSave));
                bw.write(jTextArea.getText());
                saved=true;
                //System.out.println("Save as file: " + fileToSave.getAbsolutePath());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            finally
            {
                if(bw != null)
                {
                    try {
                        bw.close();
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        }
        else
        {
            canceled=true;
        }
    }//GEN-LAST:event_jMenuSaveAsActionPerformed

    private void jMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewActionPerformed
        jDialogNew.setVisible(true);
    }//GEN-LAST:event_jMenuNewActionPerformed

    private void jButtonConfYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfYesActionPerformed
        jMenuSaveActionPerformed(evt);
        if(!canceled)
        {
            newFile();
        }
        else
        {
            jDialogNew.dispose();
        }
        
    }//GEN-LAST:event_jButtonConfYesActionPerformed

    private void jButtonConfCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfCancelActionPerformed
        jDialogNew.dispose();
    }//GEN-LAST:event_jButtonConfCancelActionPerformed

    private void jButtonConfNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfNoActionPerformed
        newFile();
    }//GEN-LAST:event_jButtonConfNoActionPerformed

    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileActionPerformed
        jDialogExit.setVisible(true);
    }//GEN-LAST:event_jMenuFileActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void jButtonExitYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitYesActionPerformed
        jMenuSaveActionPerformed(evt);
        if(!canceled)
        {
            System.exit(0);
        }
        else
        {
            jDialogExit.dispose();
        }
    }//GEN-LAST:event_jButtonExitYesActionPerformed

    private void jButtonExitNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitNoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitNoActionPerformed

    private void jButtonExitCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitCancelActionPerformed
        jDialogExit.dispose();
    }//GEN-LAST:event_jButtonExitCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jMenuSaveActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jMenuOpenActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jDialogAbout.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void newFile()
    {
        jDialogNew.dispose();
        jTextArea.setText("");
        saved=false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonConfCancel;
    private javax.swing.JButton jButtonConfNo;
    private javax.swing.JButton jButtonConfYes;
    private javax.swing.JButton jButtonExitCancel;
    private javax.swing.JButton jButtonExitNo;
    private javax.swing.JButton jButtonExitYes;
    private javax.swing.JDialog jDialogAbout;
    private javax.swing.JDialog jDialogExit;
    private javax.swing.JDialog jDialogNew;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuNew;
    private javax.swing.JMenuItem jMenuOpen;
    private javax.swing.JMenuItem jMenuSave;
    private javax.swing.JMenuItem jMenuSaveAs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
